import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import "./index.css"

import { createRouter, RouterProvider } from "@tanstack/react-router"
import { routeTree } from "./routeTree.gen" // auto-generated by TanStack Router Vite plugin

const router = createRouter({ routeTree })

declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router
	}
}

createRoot(document.body).render(
	<StrictMode>
		<RouterProvider router={router} />
	</StrictMode>,
)
