import type { Metadata } from "next"
import "./globals.css"
import Providers from "./_providers/Providers"

export const metadata: Metadata = {
	title: "Gold App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="fa">
			<body>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	)
}
