import type { Metadata } from "next";
import Providers from "./_lib/Providers";
import MainLayout from "@/app/_components/main/MainLayout";

export const metadata: Metadata = {
  title: "Gold App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex flex-col align-middle h-screen bg-base-100 text-base-content">
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}